services:
  jupyter:
    image: msi2:1.0
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: /Users/rafalrak/studia/msi2
        target: /home/jovyan/msi2

volumes:
  jupyter-data: